# Generated by Django 5.1.7 on 2025-04-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='des',
            field=models.TextField(blank=True, null=True),
        ),
    ]
