# Generated by Django 5.0 on 2023-12-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todowork",
            name="note",
            field=models.CharField(default="dfd", max_length=500),
            preserve_default=False,
        ),
    ]
